### ISSUE TITLE
Is there a nuget package?

### ISSUE THREAD

**Issue by dotneteval** [charri/MvvmCross-Routing#1]
HI 
@charri I have been following the MvvmCross 5.0 discussions, and you said you were going to package up your plugin. I can't seem to find it in the list of available nuget packages.

Did you get a chance to create one, if so can you tell me the name you have given to it.

Thanks

**Comment by martijn00** [comment]
This is going to be integrated in 5.0: https://github.com/MvvmCross/MvvmCross/pull/1595

**Comment by dotneteval** [comment]
HI @martijn00 Yes, I understand, but I was hoping to do an evaluation using the plugin, rather than having to upgrade my app to the v5 nightly build.
Is this functionality now in the nightly build, if so I'll use that

**Comment by martijn00** [comment]
Yes it is in the nightly build.
